[2023-08-26T17:26:00.112-0300] {processor.py:157} INFO - Started process (PID=24035) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:26:00.112-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:26:00.112-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:26:00.112-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:26:00.114-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:26:00.113-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 14
    doc = json.load( inputfile )
    ^
IndentationError: expected an indented block
[2023-08-26T17:26:00.114-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:26:00.163-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.051 seconds
[2023-08-26T17:27:22.394-0300] {processor.py:157} INFO - Started process (PID=24216) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:27:22.395-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:27:22.395-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:27:22.395-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:27:22.396-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:27:22.396-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 14
    doc = json.load( inputfile )
    ^
IndentationError: expected an indented block
[2023-08-26T17:27:22.396-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:27:22.446-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.053 seconds
[2023-08-26T17:28:08.276-0300] {processor.py:157} INFO - Started process (PID=24323) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:08.277-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:28:08.278-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:28:08.277-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:08.279-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:28:08.278-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 14
    doc = json.load( inputfile )
    ^
IndentationError: expected an indented block
[2023-08-26T17:28:08.279-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:08.330-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.054 seconds
[2023-08-26T17:28:54.335-0300] {processor.py:157} INFO - Started process (PID=24424) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:54.336-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:28:54.336-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:28:54.336-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:54.346-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:28:54.346-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2023-08-26T17:28:54.346-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:28:54.397-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.062 seconds
[2023-08-26T17:29:38.958-0300] {processor.py:157} INFO - Started process (PID=24528) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:29:38.958-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:29:38.958-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:29:38.958-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:29:38.969-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:29:38.968-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2023-08-26T17:29:38.969-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:29:39.016-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.059 seconds
[2023-08-26T17:30:24.818-0300] {processor.py:157} INFO - Started process (PID=24628) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:30:24.819-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:30:24.819-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:30:24.819-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:30:24.829-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:30:24.828-0300] {dagbag.py:347} ERROR - Failed to import: /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
Traceback (most recent call last):
  File "/Users/luishmq/.pyenv/versions/3.8.13/envs/air_flow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2023-08-26T17:30:24.829-0300] {processor.py:841} WARNING - No viable dags retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:30:24.877-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.059 seconds
[2023-08-26T17:31:13.025-0300] {processor.py:157} INFO - Started process (PID=25020) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:31:13.026-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:31:13.026-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:13.026-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:31:27.852-0300] {processor.py:839} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:31:28.247-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.247-0300] {manager.py:501} INFO - Created Permission View: can edit on DAG:weather_dag
[2023-08-26T17:31:28.251-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.250-0300] {manager.py:501} INFO - Created Permission View: can delete on DAG:weather_dag
[2023-08-26T17:31:28.253-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.253-0300] {manager.py:501} INFO - Created Permission View: can read on DAG:weather_dag
[2023-08-26T17:31:28.258-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.257-0300] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-26T17:31:28.261-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.261-0300] {dag.py:2929} INFO - Creating ORM DAG for weather_dag
[2023-08-26T17:31:28.264-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:31:28.264-0300] {dag.py:3677} INFO - Setting next_dagrun for weather_dag to 2022-11-30T00:00:00+00:00, run_after=2022-11-30T01:00:00+00:00
[2023-08-26T17:31:28.272-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 15.247 seconds
[2023-08-26T17:32:15.216-0300] {processor.py:157} INFO - Started process (PID=25141) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:32:15.217-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:32:15.217-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:32:15.217-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:32:15.600-0300] {processor.py:839} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:32:15.670-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:32:15.670-0300] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-26T17:32:15.676-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:32:15.676-0300] {dag.py:3677} INFO - Setting next_dagrun for weather_dag to 2022-11-30T00:00:00+00:00, run_after=2022-11-30T01:00:00+00:00
[2023-08-26T17:32:15.683-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.468 seconds
[2023-08-26T17:38:11.349-0300] {processor.py:157} INFO - Started process (PID=25711) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:38:11.349-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:38:11.350-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:38:11.350-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:38:11.557-0300] {processor.py:839} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:38:11.661-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:38:11.661-0300] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-26T17:38:11.668-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:38:11.668-0300] {dag.py:3677} INFO - Setting next_dagrun for weather_dag to 2022-11-30T15:00:00+00:00, run_after=2022-11-30T16:00:00+00:00
[2023-08-26T17:38:11.677-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.329 seconds
[2023-08-26T17:47:36.712-0300] {processor.py:157} INFO - Started process (PID=27043) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:47:36.713-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:47:36.714-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:47:36.714-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:47:36.966-0300] {processor.py:839} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:47:37.059-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:47:37.059-0300] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-26T17:47:37.066-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:47:37.065-0300] {dag.py:3677} INFO - Setting next_dagrun for weather_dag to 2022-12-01T00:00:00+00:00, run_after=2022-12-01T01:00:00+00:00
[2023-08-26T17:47:37.073-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.361 seconds
[2023-08-26T17:50:48.163-0300] {processor.py:157} INFO - Started process (PID=27514) to work on /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:50:48.164-0300] {processor.py:829} INFO - Processing file /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py for tasks to queue
[2023-08-26T17:50:48.164-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:50:48.164-0300] {dagbag.py:539} INFO - Filling up the DagBag from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:50:48.447-0300] {processor.py:839} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py
[2023-08-26T17:50:48.524-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:50:48.524-0300] {dag.py:2907} INFO - Sync 1 DAGs
[2023-08-26T17:50:48.531-0300] {logging_mixin.py:151} INFO - [2023-08-26T17:50:48.531-0300] {dag.py:3677} INFO - Setting next_dagrun for weather_dag to 2022-12-01T06:00:00+00:00, run_after=2022-12-01T07:00:00+00:00
[2023-08-26T17:50:48.538-0300] {processor.py:179} INFO - Processing /Users/luishmq/Documents/repos/air_flow/dags/weather_dag.py took 0.375 seconds
